flaskblog/posts/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, TextAreaField
from wtforms.validators import DataRequired


class PostForm(FlaskForm):
    title = StringField('Title', validators=[DataRequired()])
    content = TextAreaField('Content', validators=[DataRequired()])
    submit = SubmitField('Post')

flaskblog/posts/routes.py
from flask import (render_template, url_for, flash,
                   redirect, request, abort, Blueprint)
from flask_login import current_user, login_required
from flaskblog import db
from flaskblog.models import Post
from flaskblog.posts.forms import PostForm

posts = Blueprint('posts', __name__)


@posts.route("/post/new", methods=['GET', 'POST'])
@login_required
def new_post():
    form = PostForm()
    if form.validate_on_submit():
        post = Post(title=form.title.data, content=form.content.data, author=current_user)
        db.session.add(post)
        db.session.commit()
        flash('Your post has been created!', 'success')
        return redirect(url_for('main.blog'))
    return render_template('create_post.html', title='New Post',
                           form=form, legend='New Post')


@posts.route("/post/<int:post_id>")
def post(post_id):
    post = Post.query.get_or_404(post_id)
    return render_template('post.html', title=post.title, post=post)


@posts.route("/post/<int:post_id>/update", methods=['GET', 'POST'])
@login_required
def update_post(post_id):
    post = Post.query.get_or_404(post_id)
    if post.author != current_user:
        abort(403)
    form = PostForm()
    if form.validate_on_submit():
        post.title = form.title.data
        post.content = form.content.data
        db.session.commit()
        flash('Your post has been updated!', 'success')
        return redirect(url_for('posts.post', post_id=post.id))
    elif request.method == 'GET':
        form.title.data = post.title
        form.content.data = post.content
    return render_template('create_post.html', title='Update Post',
                           form=form, legend='Update Post')


@posts.route("/post/<int:post_id>/delete", methods=['POST'])
@login_required
def delete_post(post_id):
    post = Post.query.get_or_404(post_id)
    if post.author != current_user:
        abort(403)
    db.session.delete(post)
    db.session.commit()
    flash('Your post has been deleted!', 'success')
    return redirect(url_for('main.blog'))

flaskblog/users/routes.py
from flask import render_template, url_for, flash, redirect, request, Blueprint
from flask_login import login_user, current_user, logout_user, login_required
from flaskblog import db, bcrypt
from flaskblog.models import User, Post
from flaskblog.users.forms import (RegistrationForm, LoginForm, UpdateAccountForm,
                                   RequestResetForm, ResetPasswordForm)
from flaskblog.users.utils import save_picture, send_reset_email


users = Blueprint('users', __name__)


@users.route("/register", methods=['GET', 'POST'])
def register():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = RegistrationForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user = User(username=form.username.data, email=form.email.data, password=hashed_password)
        db.session.add(user)
        db.session.commit()
        flash(f'Your account has been created! You are now able to log in', 'success')
        return redirect(url_for('users.login'))
    return render_template('register.html', title='Register', form=form)


@users.route("/login", methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user and bcrypt.check_password_hash(user.password, form.password.data):
            login_user(user, remember=form.remember.data)
            next_page = request.args.get('next')
            return redirect(next_page) if next_page else redirect(url_for('main.blog'))
        else:
            flash('Login Unsuccessful. Please check email and password', 'danger')
    return render_template('login.html', title='Login', form=form)


@users.route("/logout")
def logout():
    logout_user()
    return redirect(url_for('main.blog'))


@users.route("/account", methods=['GET', 'POST'])
@login_required
def account():
    form = UpdateAccountForm()
    if form.validate_on_submit():
        if form.picture.data:
            picture_file = save_picture(form.picture.data)
            current_user.image_file = picture_file
        current_user.username = form.username.data
        current_user.email = form.email.data
        db.session.commit()
        flash('Your account has been updated!', 'success')
        return redirect(url_for('users.account'))
    elif request.method == 'GET':
        form.username.data = current_user.username
        form.email.data = current_user.email
    image_file = url_for('static', filename='profile_pics/' + current_user.image_file)
    return render_template('account.html', title='Account',
                           image_file=image_file, form=form)


@users.route("/user/<string:username>")
def user_posts(username):
    page = request.args.get('page', 1, type=int)
    user = User.query.filter_by(username=username).first_or_404()
    posts = Post.query.filter_by(author=user)\
        .order_by(Post.date_posted.desc())\
        .paginate(page=page, per_page=5)
    return render_template('user_posts.html', posts=posts, user=user)


@users.route("/reset_password", methods=['GET', 'POST'])
def reset_request():
    if current_user.is_authenticated:
        return redirect(url_for('main.blog'))
    form = RequestResetForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        send_reset_email(user)
        flash('An email has been sent with instructions to reset your password.', 'info')
        return redirect(url_for('users.login'))
    return render_template('reset_request.html', title='Reset Password', form=form)


@users.route("/reset_password/<token>", methods=['GET', 'POST'])
def reset_token(token):
    if current_user.is_authenticated:
        return redirect(url_for('main.blog'))
    user = User.verify_reset_token(token)
    if user is None:
        flash('That is an invalid or expired token', 'warning')
        return redirect(url_for('users.reset_request'))
    form = ResetPasswordForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user.password = hashed_password
        db.session.commit()
        flash('Your password has been updated! You are now able to log in', 'success')
        return redirect(url_for('users.login'))
    return render_template('reset_token.html', title='Reset Password', form=form)

flaskblog/templates/about.html
{% extends "layout.html" %}
{% block content %}
    <h1>About Page</h1>
    <p>The M3 Consulting Technology Blog is a modified version of the Corey Schafer Flask tutorial with database.
        The posts are visible to anyone who visits the page, and registered users can write a new post.
        Registered users can also edit and delete their posts. There is a user profile page where users can upload
        a profile picture, which is scaled down to a size of 125x125.
    </p>
    <p>Register your free account, Login, and try it out.</p>
{% endblock content %}

flaskblog/templates/account.html
{% extends "layout.html" %}
{% block content %}
    <h1>M3 Technology Blog</h1>
    <div class="content-section">
        <div class="d-flex media pt-2">
            <img class="rounded-circle account-img" src="{{ image_file }}">
            <div class="media-body">
              <h2 class="account-heading">{{ current_user.username }}</h2>
              <p class="text-secondary">{{ current_user.email }}</p>
            </div>
        </div>
        <form method="POST" action="" enctype="multipart/form-data">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Account Info</legend>
    <!--                build registration form in html with flask object attributes and methods -->
                <div class="form-group mb-4">
                    {{ form.username.label(class="form-control-label") }}

                    {% if form.username.errors %}
                        {{ form.username(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.username.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.username(class="form-control form-control-lg") }}
                    {% endif %}

                </div>
                <div class="form-group mb-4">
                    {{ form.email.label(class="form-control-label") }}
                    {% if form.email.errors %}
                        {{ form.email(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.email.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.email(class="form-control form-control-lg") }}
                    {% endif %}
    <!--                    {{ form.email(class="form-control form-control-lg") }}-->
                </div>
                <div class="form-group">
                    {{ form.picture.label() }}</br>
                    {{ form.picture(class="form-control-file") }}
                    {% if form.picture.errors %}
                        {% for error in form.picture.errors %}
                            </br><span class="text-danger">{{ error }}</span>
                        {% endfor %}
                    {% endif %}
                </div>
            </fieldset>
    <!--            build submit button margin AND padding to get the spacing just right -->
            <div class="form-group py-3 mt-3">
                {{ form.submit(class="btn btn-outline-info") }}
            </div>
        </form>
    </div>
{% endblock content %}

flaskblog/templates/blog.html
{% extends "layout.html" %}
{% block content %}
    <h1>M3 Technology Blog</h1>
<!--    get posts from database and iterate over each one putting them into html blocks-->
    {% for post in posts.items %}
        <article class="d-flex media content-section">
            <img class="rounded-circle article-img" src="{{ url_for('static', filename='profile_pics/' + post.author.image_file) }}">
          <div class="media-body">
            <div class="article-metadata">
              <a class="mr-2" href="{{ url_for('users.user_posts', username=post.author.username) }}">{{ post.author.username }}</a>
              <small class="text-muted">{{ post.date_posted.strftime('%A %b %-d, %Y') }}</small>
            </div>
            <h2><a class="article-title" href="{{ url_for('posts.post', post_id=post.id) }}">{{ post.title }}</a></h2>
            <p class="article-content">{{ post.content }}</p>
          </div>
        </article>
    {% endfor %}
    {% for page_num in posts.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=1) %}
        {% if page_num %}
          {% if posts.page == page_num %}
            <a class="btn btn-info mb-4" href="{{ url_for('main.blog', page=page_num) }}">{{ page_num }}</a>
          {% else %}
            <a class="btn btn-outline-info mb-4" href="{{ url_for('main.blog', page=page_num) }}">{{ page_num }}</a>
          {% endif %}
        {% else %}
          ...
        {% endif %}
    {% endfor %}
{% endblock content %}

flaskblog/templates/create_post.html
{% extends "layout.html" %}
{% block content %}
    <h1>M3 Technology Blog</h1>
    <div class="content-section">
        <form method="POST" action="">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">{{ legend }}</legend>
<!--                build login form in html with flask object attributes and meth    <h1>M3 Technology Blog</h1>
ods -->
                <div class="form-group mb-4">
                    {{ form.title.label(class="form-control-label") }}
                    {% if form.title.errors %}
                        {{ form.title(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.title.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.title(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group mb-4">
                    {{ form.content.label(class="form-control-label") }}
                    {% if form.content.errors %}
                        {{ form.content(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.content.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.content(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
            </fieldset>
            <div class="form-group pt-3 pb-3">
                {{ form.submit(class="btn btn-outline-info") }}
            </div>
        </form>
    </div>
{% endblock content %}

flaskblog/templates/home.html
{% extends "layout.html" %}
{% block content %}
    <div class="introduction">
        <h4>What is an operating system?</h4>
        <p>An Operating System is the first bit of software that gets put on a computer.
            The two most famous operating systems are Mac and Windows, but there are other operating systems too.
            Linux is one of those other operating systems. On top of the operating system, a computer has apps,
            just like a phone has apps. Sometimes an app has versions for multiple operating systems, like Chrome.
            The Chrome app can run on Mac or windows or your phone. (the phone has an operating system too)</p>
        <p>What does an operating system do? It works with the hardware. The keyboard, mouse and monitor are
            some of the hardware it works with. The processor, memory, and disk drives are also hardware that
            works with the operating system. The job of the operating system is to make the hardware available to
            the apps that run on it. Not only that, the operating system is also in charge of moving and saving data.
            Every byte of data in the system goes through the operating system. In a personal computer (PC) the data
            goes from the keyboard to the monitor, then from the monitor to the disk drive or internet.</p>
        <h4>The Linux operating system powers the internet, and it can power your home and business too!</h4>
        <p>Linux operating systems have been in use and evolving for 30 years, involving thousands of
            programmers from all over the world. Linux is far more stable than MS Windows or Mac OS
            which is why IT professionals choose Linux for their internet servers.</p>
        <p>With that in mind, I would like to ask you some questions.</p>
    </div>
    <div class="questions">
        <ul>
            <li>Does your computer ever freeze up, or do things you did not tell it to do?</li>
            <li>Does your PC upgrade itself automatically, even when you turn auto-upgrade off?</li>
            <li>Are you comfortable with your computer recording everything you do and <br>
                sending that data to a server somewhere without your knowledge or consent?</li>
        </ul>
    </div>
    <div class="answers">
        <p>If you answered yes to any of those questions, there is another option!<br>
        Free and Open Source Software; FOSS<br>
        and a Linux operating system<br><br>
        M3 Consulting will help you convert your PC to the freedom of choice and Open Source</p>
    </div>

{% endblock content %}

flaskblog/templates/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
    <!-- local css -->
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/main.css') }}">
    <link rel="shortcut icon" href="{{ url_for('static', filename='favicon.ico') }}">

    <!-- the page title can be dynamic -->
    {% if title %}
        <title>M3Consulting - {{ title }}</title>
    {% else %}
        <title>M3Consulting</title>
    {% endif %}
</head>
<body>
<!--    page header contains navigation bar-->
    <header class="container">
        <div class="row">
            <div class="col-3"></div>
            <div class="col-6">
    <!-- banner graphic -->
                <img id="myLogo" class="img-fluid" src="{{ url_for('static', filename='img/ConsultLogoOneLine.png') }}">
                <h5>Your local advocate for free and open source software</h5>
            </div>

            <div class="col-3"></div>
        </div>
    </header>

    <nav class="navbar navbar-expand-md navbar-dark bg-blue">
        <div class="container">
            <a class="navbar-brand mr-4" href="/">M3Consulting Menu</a>
<!-- this will collapse the nav menu into a "hamburger" button drop down menu when viewed on small screen-->
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarToggle">
              <div class="navbar-nav mr-auto">
                  <a class="nav-item nav-link" href="https://m3consulting.xyz/">Home</a>
                  <a class="nav-item nav-link" href="https://m3consulting.xyz/about">About</a>
                  <a class="nav-item nav-link" href="{{ url_for('main.blog') }}">Blog</a>
                  <a class="nav-item nav-link" href="https://m3consulting.xyz/links">Resource Database</a>
              </div>
<!-- Navbar Right Side -->
              <div class="navbar-nav ms-auto">
                  {% if current_user.is_authenticated %}
                    <a class="nav-item nav-link" href="{{ url_for('posts.new_post') }}">New Post</a>
                    <a class="nav-item nav-link" href="{{ url_for('users.account') }}">Account</a>
                    <a class="nav-item nav-link" href="{{ url_for('users.logout') }}">Logout</a>
                  {% else %}
                    <a class="nav-item nav-link" href="{{ url_for('users.login') }}">Login</a>
                    <a class="nav-item nav-link" href="{{ url_for('users.register') }}">Register</a>
                  {% endif %}
              </div>
          </div>
        </div>
    </nav>

    <main role="main" class="container mt-4">
        <div class="row">
<!-- posts get 8 columns of width-->
            <div class="col-md-8">
<!-- messages if present show at top of posts -->
                {% with messages = get_flashed_messages(with_categories=true) %}
                    {% if messages %}
                        {% for category, message in messages %}
<!-- bootstrap creates colored box for message to display in-->
                            <div class="alert alert-{{ category }}">
                               {{ message }}
                            </div>
                        {% endfor %}
                    {% endif %}
                {% endwith %}
                {% block content %}{% endblock %}
            </div>
<!-- sidebar gets 4 colums of width-->
            <div class="col-md-4">
                <div class="fungraphic">
                    <img class="img-fluid" src="{{ url_for('static', filename='img/LinuxRoot.png') }}" alt="Fun Graphic">
                </div>
                <div class="content-section">
                    <h3>GOT AN OLD COMPUTER?</h3>
                        <p>Is your computer old, sluggish, tired, or just not working as well as it once did? Does the box and monitor look perfectly fine?</p>
                        <p>Don’t change the computer, change the software that runs on it. There is a huge assortment of free and open source
                            software that will bring new life to that tired old computer.</p>
                        <h4>Contact Macks at M3Consulting to find out more.</h4>
<!--                        <h5>call or text: 603.801.2853</h5>-->
<!--                        <h5>email: m3consulting@pm.me</h5>-->
<!--                        <h5>website: m3consulting.xyz</h>-->
                </div>
                <div class="pt-4 tagLine">
                    <p>Contact M3Consulting for help with</p>
                    <ul>
                        <li>Operating system upgrades</li>
                        <li>Website development and hosting</li>
                        <li>Computer and network troubleshooting</li>
                        <li>Education and training services</li>
                    </ul>
                </div>
            </div>
        </div>
    </main>

    <footer>
        <h3>Take back your Digital Freedom!</h3>
        <h5>email: m3consulting@pm.me - call or text: 603.801.2853</h5>
    </footer>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body>
</html>

flaskblog/templates/login.html
{% extends "layout.html" %}
{% block content %}
    <h1>M3 Technology Blog</h1>
    <div class="content-section">
        <form method="POST" action="">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Log In</legend>
<!--                build login form in html with flask object attributes and methods -->
                <div class="form-group mb-4">
                    {{ form.email.label(class="form-control-label") }}
                    {% if form.email.errors %}
                        {{ form.email(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.email.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.email(class="form-control form-control-lg") }}
                    {% endif %}
<!--                    {{ form.email(class="form-control form-control-lg") }}-->
                </div>
                <div class="form-group mb-4">
                    {{ form.password.label(class="form-control-label") }}
                    {% if form.password.errors %}
                        {{ form.password(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.password.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.password(class="form-control form-control-lg") }}
                    {% endif %}
<!--                    {{ form.password(class="form-control form-control-lg") }}-->
                </div>
                <div class="form-check">
                    {{ form.remember(class="form-check-input") }}
                    {{ form.remember.label(class="form-check-label") }}
                </div>
            </fieldset>
            <div class="form-group pt-3 pb-3 pr-3">
                {{ form.submit(class="btn btn-outline-info") }}
                <small class="text-muted ml-3">
                    <a href="{{ url_for('users.reset_request') }}">Forgot Password?</a>
                </small>
            </div>
        </form>
    </div>
    <div class="border-top pt-3">
        <small class="text-muted">
            Need An Account? <a class="ml-2" href="{{ url_for('users.register') }}">Sign Up Now</a>
        </small>
    </div>
{% endblock content %}

flaskblog/templates/post.html
{% extends "layout.html" %}
{% block content %}
    <h1>M3 Technology Blog</h1>
    <article class="d-flex media content-section">
        <img class="rounded-circle article-img" src="{{ url_for('static', filename='profile_pics/' + post.author.image_file) }}">
        <div class="media-body">
            <div class="article-metadata">
            <a class="mr-2" href="{{ url_for('users.user_posts', username=post.author.username) }}">{{ post.author.username }}</a>
            <small class="text-muted">{{ post.date_posted.strftime('%A %b %-d, %Y') }}</small>
            {% if post.author == current_user %}
                <div>
                    <a class="btn btn-secondary btn-sm my-1" href="{{ url_for('posts.update_post', post_id=post.id) }}">Update</a>
                    <button type="button" class="btn btn-danger btn-sm m-1" data-toggle="modal" data-target="#deleteModal">Delete</button>
                </div>
            {% endif %}
        </div>
            <h2 class="article-title">{{ post.title }}</h2>
            <p class="article-content">{{ post.content }}</p>
        </div>
    </article>
    <!-- Modal -->
    <div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel" aria-hidden="true">
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title" id="deleteModalLabel">Delete Post?</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
            <form action="{{ url_for('posts.delete_post', post_id=post.id) }}" method="POST">
              <input class="btn btn-danger" type="submit" value="Delete">
            </form>
          </div>
        </div>
      </div>
    </div>
{% endblock content %}

flaskblog/templates/reset_request.html
{% extends "layout.html" %}
{% block content %}
    <h1>M3 Technology Blog</h1>
    <div class="content-section">
        <form method="POST" action="">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Reset Password</legend>
                <div class="form-group">
                    {{ form.email.label(class="form-control-label") }}
                    {% if form.email.errors %}
                        {{ form.email(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.email.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.email(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
            </fieldset>
            <div class="form-group mt-3">
                {{ form.submit(class="btn btn-outline-info") }}
            </div>
        </form>
    </div>
{% endblock content %}

flaskblog/templates/user_posts.html
{% extends "layout.html" %}
{% block content %}
    <h1>M3 Technology Blog</h1>
    <h2 class="mb-3">Posts by {{ user.username }} ({{ posts.total }})</h2>
    {% for post in posts.items %}
        <article class="d-flex media content-section">
          <img class="rounded-circle article-img" src="{{ url_for('static', filename='profile_pics/' + post.author.image_file) }}">
          <div class="media-body">
            <div class="article-metadata">
              <a class="mr-2" href="{{ url_for('users.user_posts', username=post.author.username) }}">{{ post.author.username }}</a>
              <small class="text-muted">{{ post.date_posted.strftime('%A %b %-d, %Y') }}</small>
            </div>
            <h2><a class="article-title" href="{{ url_for('posts.post', post_id=post.id) }}">{{ post.title }}</a></h2>
            <p class="article-content">{{ post.content }}</p>
          </div>
        </article>
    {% endfor %}
    {% for page_num in posts.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
      {% if page_num %}
        {% if posts.page == page_num %}
          <a class="btn btn-info mb-4" href="{{ url_for('users.user_posts', username=user.username, page=page_num) }}">{{ page_num }}</a>
        {% else %}
          <a class="btn btn-outline-info mb-4" href="{{ url_for('users.user_posts', username=user.username, page=page_num) }}">{{ page_num }}</a>
        {% endif %}
      {% else %}
        ...
      {% endif %}
    {% endfor %}
{% endblock content %}